### ISSUE TITLE
Specify minimum compiler version in package-set release

### ISSUE THREAD

**Issue by f-f** [spacchetti/spacchetti#63]
As detailed in https://github.com/spacchetti/spago/issues/98#issuecomment-461131045, we should start prefixing releases with the minimum compiler version in which the package-set is expected to work, as `purescript/package-sets` does already

**Comment by justinwoo** [comment]
Do you just want `purs-0.12.2-20190207`?

**Comment by f-f** [comment]
@justinwoo why the prefix?

**Comment by justinwoo** [comment]
so it shoul dbe `0.12.2-20190207`?

**Comment by f-f** [comment]
@justinwoo yeah that's good by me 👍

**Comment by f-f** [comment]
Thanks @justinwoo ❤️
